services:
  
  acl-customer-adapter:
    container_name: acl-customer-adapter
    image: acl-customer-adapter
    build:
      context: ./acl-customer-adapter
      dockerfile: Dockerfile
    env_file:
      - ./acl-customer-adapter/.env
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m"
    ports:
      - "9090:9090"
    expose:
      - "3001"
    networks:
      - banknet
    restart: unless-stopped   
 
networks:
  banknet:
    external: true
